# Generated by Django 4.0 on 2021-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/pic/'),
        ),
    ]
