# Generated by Django 4.0 on 2021-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/<built-in method now of type object at 0x00007FFA2C0E5F10>/'),
        ),
    ]
