# Generated by Django 4.0 on 2021-12-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chats',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chats.chatroom'),
            preserve_default=False,
        ),
    ]
