# Generated by Django 4.0 on 2021-12-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_chatroom_chats_message_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
