# Generated by Django 4.0 on 2021-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/<built-in method now of type object at 0x00007FF9A5DA5F10>/'),
        ),
    ]
