# Generated by Django 4.0 on 2021-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chatroom_users_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/<built-in method now of type object at 0x00007FFCEC9F5F10>/'),
        ),
    ]
